# Dependabot configuration
version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: America/Phoenix
    assignees:
      - ahenriksen-inferno
    labels:
      - 'type: ci'
    commit-message:
      prefix: 'ci(github-actions): '
    versioning-strategy: auto
    groups:
      github-actions:
        patterns: [ '*' ]
